// @vitest-environment jsdom

import { vi } from "vitest";
import type { SplitPaneStoreState } from "../domains/workbench/state/splitPaneStore";
import type { TabStoreState } from "../domains/workbench/state/tabStore";
import type { WorkspaceStoreState } from "../domains/workspace/state/workspaceStore";
import type { ShortContext } from "./keybindings";

/** Creates a complete shortcut context with overridable test doubles. */
export function createShortcutContext(input: Partial<ShortContext> = {}): ShortContext {
  return {
    pathname: "/",
    isWorkspaceRoute: true,
    isPopupOpen: false,
    tabStoreState: {
      tabs: [
        {
          id: "tab-1",
          workspaceId: "workspace-1",
          title: "Tab 1",
          pinned: false,
          kind: "terminal",
          data: { title: "Terminal" },
        },
      ],
      selectedTabId: "tab-1",
      selectedTabIdByWorkspaceId: {},
      getWorkspaceTabs: vi.fn(() => [
        {
          id: "tab-1",
          workspaceId: "workspace-1",
          title: "Tab 1",
          pinned: false,
          kind: "terminal",
          data: { title: "Terminal" },
        },
      ]),
      resolveTabForWorkspace: vi.fn(),
      selectTab: vi.fn(),
      retainWorkspaceTabs: vi.fn(() => []),
      openTab: vi.fn(),
      closeTab: vi.fn(),
      closeOtherTabs: vi.fn(),
      closeAllTabs: vi.fn(),
      closeAllTerminalTabs: vi.fn(),
      setTerminalTabSessionId: vi.fn(),
      setAgentChatTabRuntime: vi.fn(),
      setAgentChatTabSession: vi.fn(),
      setAgentChatTabDSHModel: vi.fn(),
      setAgentChatTabSubagentControl: vi.fn(),
      setTerminalTabAgentKind: vi.fn(),
      setBrowserTabFaviconUrl: vi.fn(),
      setBrowserTabUrl: vi.fn(),
      toggleTabPinned: vi.fn(),
      promoteTemporaryTab: vi.fn(),
      reorderTab: vi.fn(),
      renameTab: vi.fn(),
      renameTabsForEntryRename: vi.fn(),
      setFileTabDirty: vi.fn(),
      refreshFileTabFromDisk: vi.fn(),
    } as TabStoreState,
    activeWorkspaceId: "workspace-1",
    workspaceStoreState: {
      projects: [],
      workspaces: [],
      pullRequestByWorkspaceId: {},
      latestPullRequestByWorkspaceId: {},
      currentBranchByWorkspaceId: {},
      gitChangesCountByWorkspaceId: {},
      gitChangeTotalsByWorkspaceId: {},
      gitRefreshVersionByWorktreePath: {},
      fileTreeChangedRelativePathsByWorktreePath: {},
      displayProjectIds: [],
      isProjectsLoaded: true,
      lastUsedExternalAppId: undefined,
      organizationPreferencesById: {},
      fileTreeRefreshVersion: 0,
      workspaceListHierarchyMode: "by_project",
      orderedWorkspaceIds: [],
      setDisplayProjectIds: vi.fn(),
      setLastUsedExternalAppId: vi.fn(),
      setWorkspaceListHierarchyMode: vi.fn(),
      load: vi.fn(),
      createProject: vi.fn(),
      deleteProject: vi.fn(),
      updateProjectConfig: vi.fn(),
      incrementFileTreeRefreshVersion: vi.fn(),
      addWorkspace: vi.fn(),
      removeWorkspace: vi.fn(),
      renameWorkspace: vi.fn(),
      renameWorkspaceBranch: vi.fn(),
      reorderWorkspace: vi.fn(),
      setWorkspaceGitChangesCount: vi.fn(),
      setWorkspaceGitChangeTotals: vi.fn(),
      setWorkspacePullRequest: vi.fn(),
      setWorkspaceCurrentBranch: vi.fn(),
      incrementGitRefreshVersion: vi.fn(),
      loadLocalFolders: vi.fn(),
      addLocalFolder: vi.fn(),
      removeLocalFolder: vi.fn(),
      setOrderedWorkspaceIds: vi.fn(),
    } as WorkspaceStoreState,

    splitPaneStoreState: {
      layoutByWorkspaceId: {},
      getLayout: vi.fn(),
      getActivePane: vi.fn(() => null),
      getPane: vi.fn(() => null),
      getPaneForTab: vi.fn(() => null),
      getAllPanes: vi.fn(() => []),
      setActivePane: vi.fn(),
      selectTab: vi.fn(),
      registerTabInPane: vi.fn(),
      unregisterTabFromPane: vi.fn(),
      createAdjacentPaneWithTab: vi.fn(),
      splitPane: vi.fn(),
      moveTab: vi.fn(),
      reorderTab: vi.fn(),
      updateSplitRatio: vi.fn(),
    } as SplitPaneStoreState,
    terminalTabTitle: "terminal.title",
    commands: {
      setSelectedRepoId: vi.fn(),
      setSelectedWorkspaceId: vi.fn(),
      load: vi.fn(async () => {}),
      createProject: vi.fn(async () => {}),
      deleteProject: vi.fn(async () => {}),
      updateProjectConfig: vi.fn(async () => {}),
      createWorkspace: vi.fn(async () => {}),
      closeWorkspace: vi.fn(async () => {}),
      refreshWorkspaceGitChanges: vi.fn(async () => {}),
      selectTab: vi.fn(),
      createTab: vi.fn(async () => {}),
      openTab: vi.fn(),
      closeTab: vi.fn(),
      closeOtherTabs: vi.fn(),
      closeAllTabs: vi.fn(),
      toggleTabPinned: vi.fn(),
      promoteTemporaryTab: vi.fn(),
      reorderTab: vi.fn(),
      renameTab: vi.fn(),
      setFileTabDirty: vi.fn(),
      refreshFileTabFromDisk: vi.fn(),

      setDisplayRepoIds: vi.fn(),
      setLeftPaneWidth: vi.fn(),
      setRightPaneWidth: vi.fn(),
      toggleLeftPaneVisibility: vi.fn(),
      toggleRightPaneVisibility: vi.fn(),
      activateWorkspacePane: vi.fn(),
      openCreateWorkspaceDialog: vi.fn(),
      focusWorkspaceFileTree: vi.fn(),
      openWorkspaceFileSearch: vi.fn(),
      renameWorkspace: vi.fn(),
      reorderWorkspace: vi.fn(),
      renameWorkspaceBranch: vi.fn(),
    } as unknown as ShortContext["commands"],
    navigate: vi.fn(),
    ...input,
  };
}
