import { createCssThemeVariables as createLatestCssThemeVariables } from "@yishan-io/design-tokens/css";
import { type CssThemeVariables, createCssThemeVariables } from "@yishan-io/design-tokens/v1/css";
import { describe, expect, it } from "vitest";

describe("createCssThemeVariables", () => {
  it("returns the exact light-mode semantic variable map", () => {
    const variables: CssThemeVariables = createCssThemeVariables("light");

    expect(variables).toEqual({
      "--yishan-color-background-app": "#f7f8fa",
      "--yishan-color-background-editor": "#ffffff",
      "--yishan-color-background-surface": "#ffffff",
      "--yishan-color-border-default": "#d8dde4",
      "--yishan-color-text-secondary": "#566761",
      "--yishan-color-editor-foreground": "#1f2430",
      "--yishan-color-editor-line-number": "#7a8190",
      "--yishan-color-editor-cursor": "#2a2a31",
      "--yishan-color-editor-gutter": "#f5f6f8",
      "--yishan-color-syntax-comment": "#7a8190",
      "--yishan-color-syntax-keyword": "#8a3ffc",
      "--yishan-color-syntax-string": "#2d7a00",
      "--yishan-color-syntax-number": "#bd5500",
      "--yishan-color-syntax-constant": "#9a6100",
      "--yishan-color-syntax-function": "#0060b8",
      "--yishan-color-syntax-type": "#006b99",
      "--yishan-color-syntax-tag": "#b04900",
      "--yishan-color-syntax-attribute": "#0b6ea8",
      "--yishan-color-syntax-operator": "#3f4758",
      "--yishan-color-syntax-delimiter": "#3f4758",
      "--yishan-color-syntax-variable": "#1f2430",
      "--yishan-color-action-selected": "#eceff3",
      "--yishan-color-action-hover": "#f3f4f6",
      "--yishan-color-git-diff-added": "#2ea043",
      "--yishan-color-git-diff-modified": "#1a7fd4",
      "--yishan-color-git-diff-deleted": "#f85149",
      "--yishan-color-git-inline-added-foreground": "#116329",
      "--yishan-color-git-inline-added-background": "#dafbe1",
      "--yishan-color-git-inline-deleted-foreground": "#82071e",
      "--yishan-color-git-inline-deleted-background": "#ffebe9",
      "--yishan-color-git-pierre-fallback-added": "#0dbe4e",
      "--yishan-color-git-pierre-fallback-deleted": "#ff2e3f",
    });
    expect(Object.keys(variables)).toEqual([
      "--yishan-color-background-app",
      "--yishan-color-background-editor",
      "--yishan-color-background-surface",
      "--yishan-color-border-default",
      "--yishan-color-text-secondary",
      "--yishan-color-editor-foreground",
      "--yishan-color-editor-line-number",
      "--yishan-color-editor-cursor",
      "--yishan-color-editor-gutter",
      "--yishan-color-syntax-comment",
      "--yishan-color-syntax-keyword",
      "--yishan-color-syntax-string",
      "--yishan-color-syntax-number",
      "--yishan-color-syntax-constant",
      "--yishan-color-syntax-function",
      "--yishan-color-syntax-type",
      "--yishan-color-syntax-tag",
      "--yishan-color-syntax-attribute",
      "--yishan-color-syntax-operator",
      "--yishan-color-syntax-delimiter",
      "--yishan-color-syntax-variable",
      "--yishan-color-action-selected",
      "--yishan-color-action-hover",
      "--yishan-color-git-diff-added",
      "--yishan-color-git-diff-modified",
      "--yishan-color-git-diff-deleted",
      "--yishan-color-git-inline-added-foreground",
      "--yishan-color-git-inline-added-background",
      "--yishan-color-git-inline-deleted-foreground",
      "--yishan-color-git-inline-deleted-background",
      "--yishan-color-git-pierre-fallback-added",
      "--yishan-color-git-pierre-fallback-deleted",
    ]);
  });

  it("returns the exact dark-mode semantic variable map", () => {
    const variables = createCssThemeVariables("dark");

    expect(variables).toEqual({
      "--yishan-color-background-app": "#2b3038",
      "--yishan-color-background-editor": "#292e36",
      "--yishan-color-background-surface": "#31363f",
      "--yishan-color-border-default": "#414754",
      "--yishan-color-text-secondary": "#cfd5dd",
      "--yishan-color-editor-foreground": "#d4dbe8",
      "--yishan-color-editor-line-number": "#8e97ab",
      "--yishan-color-editor-cursor": "#d7deef",
      "--yishan-color-editor-gutter": "#2e333c",
      "--yishan-color-syntax-comment": "#7f8796",
      "--yishan-color-syntax-keyword": "#c49fff",
      "--yishan-color-syntax-string": "#a7d56d",
      "--yishan-color-syntax-number": "#ffa86f",
      "--yishan-color-syntax-constant": "#ffd57a",
      "--yishan-color-syntax-function": "#79c4ff",
      "--yishan-color-syntax-type": "#8ad9ff",
      "--yishan-color-syntax-tag": "#ffb86b",
      "--yishan-color-syntax-attribute": "#86d0ff",
      "--yishan-color-syntax-operator": "#c0c8d8",
      "--yishan-color-syntax-delimiter": "#c0c8d8",
      "--yishan-color-syntax-variable": "#d4dbe8",
      "--yishan-color-action-selected": "rgba(221, 226, 233, 0.08)",
      "--yishan-color-action-hover": "rgba(221, 226, 233, 0.12)",
      "--yishan-color-git-diff-added": "#3fb950",
      "--yishan-color-git-diff-modified": "#58a6ff",
      "--yishan-color-git-diff-deleted": "#f85149",
      "--yishan-color-git-inline-added-foreground": "#7ee787",
      "--yishan-color-git-inline-added-background": "rgba(63, 185, 80, 0.15)",
      "--yishan-color-git-inline-deleted-foreground": "#ffa198",
      "--yishan-color-git-inline-deleted-background": "rgba(248, 81, 73, 0.15)",
      "--yishan-color-git-pierre-fallback-added": "#0dbe4e",
      "--yishan-color-git-pierre-fallback-deleted": "#ff2e3f",
    });
    expect(Object.keys(variables)).toEqual([
      "--yishan-color-background-app",
      "--yishan-color-background-editor",
      "--yishan-color-background-surface",
      "--yishan-color-border-default",
      "--yishan-color-text-secondary",
      "--yishan-color-editor-foreground",
      "--yishan-color-editor-line-number",
      "--yishan-color-editor-cursor",
      "--yishan-color-editor-gutter",
      "--yishan-color-syntax-comment",
      "--yishan-color-syntax-keyword",
      "--yishan-color-syntax-string",
      "--yishan-color-syntax-number",
      "--yishan-color-syntax-constant",
      "--yishan-color-syntax-function",
      "--yishan-color-syntax-type",
      "--yishan-color-syntax-tag",
      "--yishan-color-syntax-attribute",
      "--yishan-color-syntax-operator",
      "--yishan-color-syntax-delimiter",
      "--yishan-color-syntax-variable",
      "--yishan-color-action-selected",
      "--yishan-color-action-hover",
      "--yishan-color-git-diff-added",
      "--yishan-color-git-diff-modified",
      "--yishan-color-git-diff-deleted",
      "--yishan-color-git-inline-added-foreground",
      "--yishan-color-git-inline-added-background",
      "--yishan-color-git-inline-deleted-foreground",
      "--yishan-color-git-inline-deleted-background",
      "--yishan-color-git-pierre-fallback-added",
      "--yishan-color-git-pierre-fallback-deleted",
    ]);
  });

  it("exposes the versioned factory through the latest CSS subpath alias", () => {
    expect(createLatestCssThemeVariables("dark")).toEqual(createCssThemeVariables("dark"));
  });
});
