package daemon

const (
	MethodDaemonPing = "daemon.ping"

	MethodList                        = "list"
	MethodWorkspaceCreate             = "workspace.create"
	MethodWorkspaceClose              = "workspace.close"
	MethodWorkspaceRefreshPullRequest = "workspace.refreshPullRequest"
	MethodWorkspaceSetActive          = "workspace.setActive"
	MethodWorkspaceSyncContextLink    = "workspace.syncContextLink"
	MethodWorkspaceHealth             = "workspace.health"
	MethodWorkspaceRepair             = "workspace.repair"
	MethodWorkspaceForget             = "workspace.forget"
	MethodWorkspaceOpenProject        = "workspace.openProject"
	MethodWorkspaceCloseProject       = "workspace.closeProject"

	MethodContextGetState         = "context.getState"
	MethodContextSetCurrentOrg    = "context.setCurrentOrg"
	MethodContextSetActiveProject = "context.setActiveProject"
	MethodContextSetActiveFile    = "context.setActiveFile"

	MethodComputerHealth                 = "computer.health"
	MethodComputerPermissions            = "computer.permissions"
	MethodComputerOpenPermissionSettings = "computer.openPermissionSettings"
	MethodComputerListDisplays           = "computer.listDisplays"
	MethodComputerListApplications       = "computer.listApplications"
	MethodComputerListWindows            = "computer.listWindows"
	MethodComputerCaptureDisplay         = "computer.captureDisplay"
	MethodComputerCaptureWindow          = "computer.captureWindow"
	MethodComputerGetUITree              = "computer.getUITree"
	MethodComputerPerformAction          = "computer.performAction"
	MethodComputerFocusWindow            = "computer.focusWindow"
	MethodComputerLaunchApplication      = "computer.launchApplication"
	MethodComputerMovePointer            = "computer.movePointer"
	MethodComputerClick                  = "computer.click"
	MethodComputerDrag                   = "computer.drag"
	MethodComputerScroll                 = "computer.scroll"
	MethodComputerTypeText               = "computer.typeText"
	MethodComputerSendKey                = "computer.sendKey"
	MethodComputerReadClipboard          = "computer.readClipboard"
	MethodComputerWriteClipboard         = "computer.writeClipboard"

	MethodProjectList = "project.list"
	MethodNodeList    = "node.list"

	MethodAgentListDetectionStatuses = "agent.listDetectionStatuses"
	MethodAgentListModels            = "agent.listModels"
	MethodIntegrationGitHubStatus    = "integration.githubStatus"
	MethodCLIToolListStatuses        = "cliTools.listStatuses"

	MethodSkillList            = "skill.list"
	MethodSkillInfo            = "skill.info"
	MethodSkillAdd             = "skill.add"
	MethodSkillRemove          = "skill.remove"
	MethodSkillUpdate          = "skill.update"
	MethodSkillDetail          = "skill.detail"
	MethodFrontendEventsStream = "events.frontendStream"
	MethodAppPersistAuthTokens = "app.persistAuthTokens"
	MethodAppGetAccessToken    = "app.getAccessToken"
	MethodAppCheckAuthStatus   = "app.checkAuthStatus"
	MethodAppLogout            = "app.logout"
	MethodAppReloadAuthConfig  = "app.reloadAuthConfig"
	MethodTokenUsageDebugState = "tokenUsage.debugState"

	MethodFileRead   = "file.read"
	MethodFileList   = "file.list"
	MethodFileSearch = "file.search"
	MethodFileStat   = "file.stat"
	MethodFileWrite  = "file.write"
	MethodFileDelete = "file.delete"
	MethodFileMove   = "file.move"
	MethodFileMkdir  = "file.mkdir"
	MethodFileDiff   = "file.diff"

	MethodGitStatus            = "git.status"
	MethodGitInspect           = "git.inspect"
	MethodGitInspectPath       = "git.inspectPath"
	MethodGitListChanges       = "git.listChanges"
	MethodGitTrack             = "git.track"
	MethodGitUnstage           = "git.unstage"
	MethodGitRevert            = "git.revert"
	MethodGitCommit            = "git.commit"
	MethodGitBranchStatus      = "git.branchStatus"
	MethodGitBranchPullRequest = "git.branchPullRequest"
	MethodGitCommitsToTarget   = "git.commitsToTarget"
	MethodGitBranchDiffSummary = "git.branchDiffSummary"
	MethodGitCommitDiff        = "git.commitDiff"
	MethodGitBranchDiff        = "git.branchDiff"
	MethodGitBranches          = "git.branches"
	MethodGitPush              = "git.push"
	MethodGitPublish           = "git.publish"
	MethodGitRenameBranch      = "git.renameBranch"
	MethodGitRemoveBranch      = "git.removeBranch"
	MethodGitPrMerge           = "git.prMerge"
	MethodGitPrClose           = "git.prClose"

	MethodGitWorktreeCreate = "git.worktree.create"
	MethodGitWorktreeRemove = "git.worktree.remove"
	MethodGitAuthorName     = "git.authorName"

	MethodTerminalStart               = "terminal.start"
	MethodTerminalSend                = "terminal.send"
	MethodTerminalRead                = "terminal.read"
	MethodTerminalStop                = "terminal.stop"
	MethodTerminalKillProcess         = "terminal.killProcess"
	MethodTerminalListSessions        = "terminal.listSessions"
	MethodTerminalListPorts           = "terminal.listDetectedPorts"
	MethodTerminalResize              = "terminal.resize"
	MethodTerminalSubscribe           = "terminal.subscribe"
	MethodTerminalUnsubscribe         = "terminal.unsubscribe"
	RelayMethodTerminalSessionChanged = "terminal.session.changed"

	MethodMemorySearch       = "memory.search"
	MethodMemoryReconcile    = "memory.reconcile"
	MethodMemoryStatus       = "memory.status"
	MethodMemoryUpdateConfig = "memory.updateConfig"
	MethodMemoryGetConfig    = "memory.getConfig"
)
