package daemon

const (
	MethodDaemonPing = "daemon.ping"

	MethodOpen                     = "open"
	MethodList                     = "list"
	MethodWorkspaceCreate          = "workspace.create"
	MethodWorkspaceClose           = "workspace.close"
	MethodWorkspaceSetActive       = "workspace.setActive"
	MethodWorkspaceSyncContextLink = "workspace.syncContextLink"

	MethodContextGetState         = "context.getState"
	MethodContextSetCurrentOrg    = "context.setCurrentOrg"
	MethodContextSetActiveProject = "context.setActiveProject"
	MethodContextSetActiveFile    = "context.setActiveFile"

	MethodProjectList = "project.list"
	MethodNodeList    = "node.list"

	MethodAgentListDetectionStatuses = "agent.listDetectionStatuses"
	MethodAgentListModels            = "agent.listModels"
	MethodIntegrationGitHubStatus    = "integration.githubStatus"
	MethodCLIToolListStatuses        = "cliTools.listStatuses"
	MethodFrontendEventsStream       = "events.frontendStream"
	MethodAppPersistAuthTokens       = "app.persistAuthTokens"
	MethodAppGetAccessToken          = "app.getAccessToken"
	MethodAppCheckAuthStatus         = "app.checkAuthStatus"
	MethodAppLogout                  = "app.logout"
	MethodAppReloadAuthConfig        = "app.reloadAuthConfig"
	MethodTokenUsageDebugState       = "tokenUsage.debugState"

	MethodFileRead   = "file.read"
	MethodFileList   = "file.list"
	MethodFileSearch = "file.search"
	MethodFileStat   = "file.stat"
	MethodFileWrite  = "file.write"
	MethodFileDelete = "file.delete"
	MethodFileMove   = "file.move"
	MethodFileMkdir  = "file.mkdir"
	MethodFileDiff   = "file.diff"

	MethodGitStatus            = "git.status"
	MethodGitInspect           = "git.inspect"
	MethodGitInspectPath       = "git.inspectPath"
	MethodGitListChanges       = "git.listChanges"
	MethodGitTrack             = "git.track"
	MethodGitUnstage           = "git.unstage"
	MethodGitRevert            = "git.revert"
	MethodGitCommit            = "git.commit"
	MethodGitBranchStatus      = "git.branchStatus"
	MethodGitBranchPullRequest = "git.branchPullRequest"
	MethodGitCommitsToTarget   = "git.commitsToTarget"
	MethodGitBranchDiffSummary = "git.branchDiffSummary"
	MethodGitCommitDiff        = "git.commitDiff"
	MethodGitBranchDiff        = "git.branchDiff"
	MethodGitBranches          = "git.branches"
	MethodGitPush              = "git.push"
	MethodGitPublish           = "git.publish"
	MethodGitRenameBranch      = "git.renameBranch"
	MethodGitRemoveBranch      = "git.removeBranch"
	MethodGitPrMerge           = "git.prMerge"
	MethodGitPrClose           = "git.prClose"

	MethodGitWorktreeCreate = "git.worktree.create"
	MethodGitWorktreeRemove = "git.worktree.remove"
	MethodGitAuthorName     = "git.authorName"

	MethodTerminalStart        = "terminal.start"
	MethodTerminalSend         = "terminal.send"
	MethodTerminalRead         = "terminal.read"
	MethodTerminalStop         = "terminal.stop"
	MethodTerminalKillProcess  = "terminal.killProcess"
	MethodTerminalListSessions = "terminal.listSessions"
	MethodTerminalListPorts    = "terminal.listDetectedPorts"
	MethodTerminalResize       = "terminal.resize"
	MethodTerminalSubscribe    = "terminal.subscribe"
	MethodTerminalUnsubscribe  = "terminal.unsubscribe"
)
