/**
 * Migration baselines recorded at desktop7 Phase 21 (2026-08-18).
 *
 * These lists freeze the CURRENT state of root `helpers` and root `ui` so the
 * migration can only shrink them. The architecture test rejects:
 *
 *   - new root Helpers files (outside ROOT_HELPERS_FILES),
 *   - new production importers of root Helpers (outside ROOT_HELPERS_IMPORTERS),
 *   - new files in `ui/hooks` (outside ROOT_UI_HOOKS_FILES),
 *   - new root UI dependency violations (outside ROOT_UI_DEP_VIOLATION_FILES),
 *     where a root UI file must not import App, Domains, API, RPC, or Helpers.
 *
 * Provisional per-file owners are recorded in ARCHITECTURE.md
 * ("Root Migration Baselines"). Remove entries here only when the owning
 * phase (desktop7 Phases 23-26) moves the file.
 */

/** Production root Helpers files at Phase 21 (25; 44 including tests). */
export const ROOT_HELPERS_FILES = [
  "helpers/binaryExtensions.ts",
  "helpers/clipboard.ts",
  "helpers/codeThemes.ts",
  "helpers/delay.ts",
  "helpers/diffSearch.ts",
  "helpers/diffTheme.ts",
  "helpers/editorLanguage.ts",
  "helpers/errorHelpers.ts",
  "helpers/excalidrawScene.ts",
  "helpers/formatters.ts",
  "helpers/generateId.ts",
  "helpers/gitGutterDiff.ts",
  "helpers/issueLinks.ts",
  "helpers/leftPaneStyles.ts",
  "helpers/monacoSetup.ts",
  "helpers/monacoThemeRules.ts",
  "helpers/pathHelpers.ts",
  "helpers/platform.ts",
  "helpers/pullRequestUtils.ts",
  "helpers/styles.ts",
  "helpers/tabHelpers.ts",
  "helpers/terminalCloseTombstones.ts",
  "helpers/terminalTabUtils.ts",
  "helpers/version.ts",
  "helpers/versionHelpers.ts",
  "helpers/withTimeout.ts",
];

/** Production files that import root Helpers at Phase 21 (139). */
export const ROOT_HELPERS_IMPORTERS = [
  "app/commands/tabCloseHandler.ts",
  "app/features/app-menu/AppMenuView.tsx",
  "app/features/launch/DaemonVersionWarningControl.tsx",
  "app/features/launch/LaunchView.tsx",
  "app/features/tab-content/useTabContentRenderer.tsx",
  "app/features/title-bar/MainPaneTitleBarView.tsx",
  "app/features/title-bar/mainPaneTitleBarHelpers.tsx",
  "app/features/workspace-shell/LeftPaneView.tsx",
  "app/features/workspace-shell/MainPaneView.tsx",
  "app/features/workspace-shell/RightPaneView.tsx",
  "app/features/workspace-shell/WorkspacePortsMenuControl.tsx",
  "domains/agent/commands/agentChatCommands.ts",
  "domains/agent/commands/chatCommands.ts",
  "domains/agent/commands/piProviderCommands.ts",
  "domains/agent/events/agentChatInboundMessage.ts",
  "domains/agent/events/agentChatPiEventShared.ts",
  "domains/agent/features/agent-chat/chat/AgentChatComposerPane.tsx",
  "domains/agent/features/agent-chat/chat/AgentChatView.tsx",
  "domains/agent/features/agent-chat/chat/ChatView.tsx",
  "domains/agent/features/agent-chat/chat/RecentAgentSessions.tsx",
  "domains/agent/features/agent-chat/chat/useVoiceRecording.ts",
  "domains/agent/features/agent-chat/session/SessionHistoryMenu.tsx",
  "domains/agent/features/agent-chat/tool-calls/DiffToolCard.tsx",
  "domains/agent/features/agent-chat/transcript/AgentMarkdownContent.tsx",
  "domains/agent/runtime/agentSessionRuntime.ts",
  "domains/agent/ui/credentials/ProviderCredentialDialog.tsx",
  "domains/browser/features/browse/hooks/useBrowserTools.ts",
  "domains/browser/features/browse/hooks/useElementInspector.ts",
  "domains/files/commands/fileCommands.ts",
  "domains/files/features/diff-viewer/diff/FileDiffViewer.tsx",
  "domains/files/features/diff-viewer/diff/MultiFileDiffViewer.tsx",
  "domains/files/features/file-editor/AudioPreview.tsx",
  "domains/files/features/file-editor/ExcalidrawFilePane.tsx",
  "domains/files/features/file-editor/FileEditor.tsx",
  "domains/files/features/file-editor/ImagePreview.tsx",
  "domains/files/features/file-editor/VditorFileEditor.tsx",
  "domains/files/features/file-editor/VideoPreview.tsx",
  "domains/files/features/file-editor/createMonacoFileEditor.ts",
  "domains/files/features/file-editor/mermaidZoomButton.ts",
  "domains/files/features/file-editor/useExcalidrawSceneSync.ts",
  "domains/files/features/file-editor/useMonacoFileEditor.ts",
  "domains/files/features/file-editor/vditorEditor.ts",
  "domains/files/features/file-manager/FileManagerView.tsx",
  "domains/files/features/file-manager/FileSearchOverlay.tsx",
  "domains/files/features/file-manager/fileTreeHelpers.ts",
  "domains/files/features/file-manager/useFileTreeCrud.ts",
  "domains/files/features/file-manager/useFileTreeGitChanges.ts",
  "domains/files/features/file-manager/useFileTreeOperations.ts",
  "domains/files/features/file-manager/useGitGutterDecorations.ts",
  "domains/files/model/fileTabPlaceholder.ts",
  "domains/files/model/gitGutterDecorations.ts",
  "domains/files/ui/markdown/markdownStyles.ts",
  "domains/git/commands/gitCommands.ts",
  "domains/git/commands/gitProjectionCommands.ts",
  "domains/git/features/changes-tab/useChangesTabActions.ts",
  "domains/git/features/changes-tab/useChangesTabState.ts",
  "domains/git/features/pull-request-tab/pullRequestTabHelpers.ts",
  "domains/git/features/pull-request-tab/usePullRequestTabActions.ts",
  "domains/git/runtime/allWorkspacesGitSyncRuntime.ts",
  "domains/node/commands/nodeCommands.ts",
  "domains/organization/commands/orgCommands.ts",
  "domains/overview/commands/overviewCommands.ts",
  "domains/overview/features/overview-dashboard/AgentKindChartView.tsx",
  "domains/overview/features/overview-dashboard/ModelBreakdownView.tsx",
  "domains/overview/features/overview-dashboard/OverviewView.tsx",
  "domains/overview/features/overview-dashboard/TokenUsageChartView.tsx",
  "domains/overview/features/overview-dashboard/WorkspaceInsightsView.tsx",
  "domains/project/commands/projectCommands.ts",
  "domains/project/features/project-config/useProjectConfigFormState.ts",
  "domains/project/features/project-list/ProjectListView.tsx",
  "domains/project/features/project-list/ProjectRow.tsx",
  "domains/project/features/project-list/useProjectListPersistence.ts",
  "domains/project/features/project-list/useProjectListTreeData.ts",
  "domains/scheduled-job/commands/scheduledJobCommands.ts",
  "domains/scheduled-job/features/scheduled-job-create/CreateScheduledJobFormView.tsx",
  "domains/scheduled-job/features/scheduled-job-detail/ScheduledJobDetailView.tsx",
  "domains/scheduled-job/features/scheduled-job-detail/ScheduledJobRunsSidebar.tsx",
  "domains/scheduled-job/features/scheduled-job-form/form/useScheduledJobFormState.ts",
  "domains/scheduled-job/features/scheduled-job-list/ScheduledJobView.tsx",
  "domains/scheduled-job/features/scheduled-job-update/EditScheduledJobDialogView.tsx",
  "domains/organization/features/manage-members/MemberSettingsView.tsx",
  "domains/settings/features/account/ServiceTokenSettingsView.tsx",
  "domains/agent/features/manage-providers/RemoveProviderDialog.tsx",
  "domains/agent/features/manage-skills/AgentSkillsCard.tsx",
  "domains/agent/features/manage-skills/AgentSkillsCardDialogs.tsx",
  "domains/settings/features/cli/CLISettingsView.tsx",
  "domains/settings/features/cli/DaemonCliInstallCard.tsx",
  "domains/settings/features/cli/PiCliInstallCard.tsx",
  "domains/agent/features/computer-use/ComputerUseSettingsView.tsx",
  "domains/agent/features/agent-definitions/AgentDefinitionDialogs.tsx",
  "domains/agent/features/agent-definitions/AgentsSettingsView.tsx",
  "domains/agent/features/agent-definitions/ExtensionsSettingsView.tsx",
  "domains/settings/features/daemon/daemonSettings/DaemonConnectionSection.tsx",
  "domains/settings/features/daemon/daemonSettings/DaemonRelaySection.tsx",
  "domains/settings/features/daemon/daemonSettings/useDaemonConnectionState.ts",
  "domains/settings/features/daemon/daemonSettings/useDaemonLogDialog.ts",
  "domains/settings/features/editor/EditorSettingsView.tsx",
  "domains/settings/features/keybindings/KeybindingsSettingsView.tsx",
  "domains/agent/features/agent-memory/MemorySettingsView.tsx",
  "domains/node/features/manage-nodes/NodesSettingsView.tsx",
  "domains/settings/features/settings-shell/SettingsView.tsx",
  "domains/terminal/features/manage-terminal-sessions/TerminalSettingsView.tsx",
  "domains/workspace/features/workspace-preferences/WorkspaceSettingsView.tsx",
  "domains/settings/hooks/useCodeTheme.ts",
  "domains/settings/state/editorSettingsStore.ts",
  "domains/settings/ui/controls/SettingsPageLayout.tsx",
  "domains/terminal/events/terminalSessionTabReconciler.ts",
  "domains/terminal/hooks/useTerminalTabLookups.ts",
  "domains/terminal/runtime/sharedTerminalResourceUsage.ts",
  "domains/terminal/runtime/terminalRecovery.ts",
  "domains/terminal/runtime/terminalSessionOrchestrator.ts",
  "domains/terminal/runtime/terminalSessionService.ts",
  "domains/workbench/features/workspace-tabs/RightPaneTabBar.tsx",
  "domains/workbench/features/workspace-tabs/pane/TabBar.tsx",
  "domains/workbench/features/workspace-tabs/pane/TabBarMenus.tsx",
  "domains/workbench/model/split-pane/operations.ts",
  "domains/workbench/runtime/openTabAutoRefreshRuntime.ts",
  "domains/workbench/state/tabStore.ts",
  "domains/workspace/commands/localFolderCommands.ts",
  "domains/workspace/commands/workspaceCloseCommand.ts",
  "domains/workspace/commands/workspaceCommands.ts",
  "domains/workspace/features/create-workspace/CreateWorkspaceDialogView.tsx",
  "domains/workspace/features/create-workspace/useCreateWorkspaceDialogState.ts",
  "domains/workspace/features/workspace-resource-usage/LeftPaneResourceUsageControl.tsx",
  "domains/workspace/features/workspace-resource-usage/WorkspaceResourceUsageControl.tsx",
  "domains/workspace/services/workspaceDisplayNames.ts",
  "domains/workspace/features/workspace-status/WorkspaceInfoPopperView.tsx",
  "domains/workspace/features/workspace-status/WorkspaceLifecycleNoticeView.tsx",
  "domains/workspace/features/workspace-status/useWorkspaceInfoHover.ts",
  "domains/workspace/model/snapshotReconciler.ts",
  "domains/workspace/state/workspace/actions.localFolders.ts",
  "domains/workspace/state/workspaceLifecycleNoticeStore.ts",
  "domains/workspace/state/workspaceStoreMutations.ts",
  "domains/workspace/ui/WorkspaceRow.tsx",
  "rpc/daemonClient.ts",
  "rpc/daemonFileClient.ts",
  "rpc/daemonTerminalClient.ts",
  "rpc/helpers.ts",
  "domains/settings/features/keybindings/KeybindingDisplay.tsx",
  "ui/hooks/useRefreshableLoader.ts",
];

/** Files in `ui/hooks` at Phase 21 (4). `ui/hooks` is migration residue;
 * domain-free React behavior moves to root `renderer/hooks`. */
export const ROOT_UI_HOOKS_FILES = [
  "ui/hooks/useContextMenuState.ts",
  "ui/hooks/useLatestRequestGuard.ts",
  "ui/hooks/useRefreshableLoader.ts",
  "ui/hooks/useSuppressNativeContextMenuWhileOpen.ts",
];

/** Root UI files that currently import App/Domains/API/RPC/Helpers (2).
 * These must move to their owning Feature/Domain in Phases 22-26. */
export const ROOT_UI_DEP_VIOLATION_FILES = [
  "ui/hooks/useRefreshableLoader.ts", // helpers/withTimeout -> root hooks
];
