export const DESKTOP_RPC_IPC_CHANNELS = {
  event: "desktop:rpc/event",
} as const;

export const HOST_IPC_CHANNELS = {
  getDesktopAppVersion: "desktop:host/get-desktop-app-version",
  openLocalFolderDialog: "desktop:host/open-local-folder-dialog",
  toggleMainWindowMaximized: "desktop:host/toggle-main-window-maximized",
  getMainWindowFullscreenState: "desktop:host/get-main-window-fullscreen-state",
  openEntryInExternalApp: "desktop:host/open-entry-in-external-app",
  listDetectedExternalAppIds: "desktop:host/list-detected-external-app-ids",
  openExternalUrl: "desktop:host/open-external-url",
  readExternalClipboardSourcePaths: "desktop:host/read-external-clipboard-source-paths",
  resolveRealPath: "desktop:host/resolve-real-path",
  copyFiles: "desktop:host/copy-files",
  writeFileBase64: "desktop:host/write-file-base64",
  loadBrowserHistory: "desktop:host/load-browser-history",
  appendBrowserHistory: "desktop:host/append-browser-history",
  dispatchNotification: "desktop:host/dispatch-notification",
  playNotificationSound: "desktop:host/play-notification-sound",
  requestMicrophoneAccess: "desktop:host/request-microphone-access",
  getPendingUpdate: "desktop:host/get-pending-update",
  dismissUpdate: "desktop:host/dismiss-update",
  checkForUpdates: "desktop:host/check-for-updates",
  downloadUpdate: "desktop:host/download-update",
  installUpdate: "desktop:host/install-update",
  getAuthStatus: "desktop:host/get-auth-status",
  login: "desktop:host/login",
  getDaemonInfo: "desktop:host/get-daemon-info",
  restartDaemon: "desktop:host/restart-daemon",
  readDaemonLog: "desktop:host/read-daemon-log",
  getDaemonQuitOnExit: "desktop:host/get-daemon-quit-on-exit",
  setDaemonQuitOnExit: "desktop:host/set-daemon-quit-on-exit",
  writeClipboardText: "desktop:host/write-clipboard-text",
} as const;
